package dennler.simple.app;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.List;

@SpringBootApplication
public class SimpleApplication implements ApplicationRunner {
  private static final String BANNER = """
           ____  _                 _           _               \s
          / ___|(_)_ __ ___  _ __ | | ___     / \\   _ __  _ __ \s
          \\___ \\| | '_ ` _ \\| '_ \\| |/ _ \\   / _ \\ | '_ \\| '_ \\\s
           ___) | | | | | | | |_) | |  __/  / ___ \\| |_) | |_) |
          |____/|_|_| |_| |_| .__/|_|\\___| /_/   \\_\\ .__/| .__/\s
                            |_|                    |_|   |_| \s
          """;

  private OutputInterface output = null;

  public static void main(String[] args) {
    SpringApplication app = new SpringApplication(SimpleApplication.class);

    // Outputs text art of "openapi generator" (generated by figlet)
    app.setBanner((env, cls, out) -> out.println(BANNER));

    app.setHeadless(true);

    app.run(args);
  }

  @Autowired
  public SimpleApplication(OutputInterface output) {
    this.output = output;
  }


  @Override
  public void run(ApplicationArguments args) throws Exception {
    String msg = "hello world";

    List<String> msgs = args.getOptionValues("message");

    if (msgs != null && !msgs.isEmpty()) {
      msg = msgs.get(0);
    }

    output.send("Application started");
    output.send(msg);
  }
}
