package dennler.simple.app;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SimpleApplication implements ApplicationRunner {
  private static final Logger LOGGER = LoggerFactory.getLogger(SimpleApplication.class);
  private static final String BANNER = """
           ____  _                 _           _               \s
          / ___|(_)_ __ ___  _ __ | | ___     / \\   _ __  _ __ \s
          \\___ \\| | '_ ` _ \\| '_ \\| |/ _ \\   / _ \\ | '_ \\| '_ \\\s
           ___) | | | | | | | |_) | |  __/  / ___ \\| |_) | |_) |
          |____/|_|_| |_| |_| .__/|_|\\___| /_/   \\_\\ .__/| .__/\s
                            |_|                    |_|   |_| \s
          """;

  public static void main(String[] args) {
    SpringApplication app = new SpringApplication(SimpleApplication.class);

    // Outputs text art of "openapi generator" (generated by figlet)
    app.setBanner((env, cls, out) -> out.println(BANNER));

    app.setHeadless(true);

    app.run(args);
  }


  @Override
  public void run(ApplicationArguments args) throws Exception {
    LOGGER.info("Application started");
    LOGGER.info("Hello World!");
  }
}
